SELECT pg_catalog.setval(pg_catalog.pg_get_serial_sequence('papel', 'papel_id'), 5, true);

INSERT INTO papel VALUES (5, 'Acesso aos relatórios de acompanhamento acadêmico', 'Acompanhamento acadêmico');


SELECT pg_catalog.setval(pg_catalog.pg_get_serial_sequence('url', 'url_id'), 73, true);

INSERT INTO url VALUES (30, '/app/aluno/config_area_aluno.php');
INSERT INTO url VALUES (31, '/app/cargo/index.php');
INSERT INTO url VALUES (32, '/app/colacao_grau/index.php');
INSERT INTO url VALUES (33, '/app/dispensa_disciplina/dispensa_aluno.php');
INSERT INTO url VALUES (34, '/app/exportar/exportar_sistec.php');
INSERT INTO url VALUES (35, '/app/matricula/matricula_aluno.php');
INSERT INTO url VALUES (36, '/app/matricula/remover_matricula/filtro.php');
INSERT INTO url VALUES (37, '/app/motivos/index.php');
INSERT INTO url VALUES (38, '/app/professores/index.php');
INSERT INTO url VALUES (39, '/app/relatorios/aprovados_reprovados/aprovados_reprovados.php');
INSERT INTO url VALUES (40, '/app/relatorios/declaracao_matricula/pesquisa_declaracao_matricula.php');
INSERT INTO url VALUES (41, '/app/relatorios/egressos/pesquisa_egressos.php');
INSERT INTO url VALUES (42, '/app/relatorios/matriculados_pessoas/pesquisa_todos_alunos_periodo.php');
INSERT INTO url VALUES (43, '/app/sagu/academico/alterar_contrato.php');
INSERT INTO url VALUES (44, '/app/sagu/academico/areas_ensino.php');
INSERT INTO url VALUES (45, '/app/sagu/academico/carimbos.php');
INSERT INTO url VALUES (46, '/app/sagu/academico/consulta_disciplinas.php');
INSERT INTO url VALUES (47, '/app/sagu/academico/consulta_disciplinas_equivalentes.php');
INSERT INTO url VALUES (48, '/app/sagu/academico/consulta_inclui_departamentos.php');
INSERT INTO url VALUES (49, '/app/sagu/academico/consulta_inclui_pre_requisito.php');
INSERT INTO url VALUES (50, '/app/sagu/academico/consulta_periodos.php');
INSERT INTO url VALUES (51, '/app/sagu/academico/coordenadores.php');
INSERT INTO url VALUES (52, '/app/sagu/academico/curso_altera.php');
INSERT INTO url VALUES (53, '/app/sagu/academico/curso_ins.php');
INSERT INTO url VALUES (54, '/app/sagu/academico/cursos_disciplinas.php');
INSERT INTO url VALUES (55, '/app/sagu/academico/cursos_disciplinas_edita.php');
INSERT INTO url VALUES (56, '/app/sagu/academico/disciplina_ofer.php');
INSERT INTO url VALUES (57, '/app/sagu/academico/documentos_edita.php');
INSERT INTO url VALUES (58, '/app/sagu/academico/novo_contrato.php');
INSERT INTO url VALUES (59, '/app/sagu/academico/pessoaf_edita.php');
INSERT INTO url VALUES (60, '/app/sagu/academico/pessoaf_inclui.php');
INSERT INTO url VALUES (61, '/app/sagu/academico/post/cursos_disciplinas.php');
INSERT INTO url VALUES (62, '/app/sagu/academico/post/cursos_disciplinas_exclui.php');
INSERT INTO url VALUES (63, '/app/sagu/academico/post/cursos_exclui.php');
INSERT INTO url VALUES (64, '/app/sagu/generico/altera_campus.php');
INSERT INTO url VALUES (65, '/app/sagu/generico/altera_cidade.php');
INSERT INTO url VALUES (66, '/app/sagu/generico/configuracao_empresa.php');
INSERT INTO url VALUES (67, '/app/sagu/generico/consulta_cidades.php');
INSERT INTO url VALUES (68, '/app/sagu/generico/consulta_inclui_estados.php');
INSERT INTO url VALUES (69, '/app/sagu/generico/consulta_inclui_instituicoes.php');
INSERT INTO url VALUES (70, '/app/sagu/generico/paises_inclui.php');
INSERT INTO url VALUES (71, '/app/sagu/generico/post/cidades_inclui.php');
INSERT INTO url VALUES (72, '/app/salas/index.php');
INSERT INTO url VALUES (73, '/app/setor/index.php');


INSERT INTO public.papel_url VALUES (1, 30);
INSERT INTO public.papel_url VALUES (1, 31);
INSERT INTO public.papel_url VALUES (1, 32);
INSERT INTO public.papel_url VALUES (1, 33);
INSERT INTO public.papel_url VALUES (1, 34);
INSERT INTO public.papel_url VALUES (1, 35);
INSERT INTO public.papel_url VALUES (1, 36);
INSERT INTO public.papel_url VALUES (1, 37);
INSERT INTO public.papel_url VALUES (1, 38);
INSERT INTO public.papel_url VALUES (1, 39);
INSERT INTO public.papel_url VALUES (1, 40);
INSERT INTO public.papel_url VALUES (1, 41);
INSERT INTO public.papel_url VALUES (1, 42);
INSERT INTO public.papel_url VALUES (1, 43);
INSERT INTO public.papel_url VALUES (1, 44);
INSERT INTO public.papel_url VALUES (1, 45);
INSERT INTO public.papel_url VALUES (1, 46);
INSERT INTO public.papel_url VALUES (1, 47);
INSERT INTO public.papel_url VALUES (1, 48);
INSERT INTO public.papel_url VALUES (1, 49);
INSERT INTO public.papel_url VALUES (1, 50);
INSERT INTO public.papel_url VALUES (1, 51);
INSERT INTO public.papel_url VALUES (1, 52);
INSERT INTO public.papel_url VALUES (1, 53);
INSERT INTO public.papel_url VALUES (1, 54);
INSERT INTO public.papel_url VALUES (1, 55);
INSERT INTO public.papel_url VALUES (1, 56);
INSERT INTO public.papel_url VALUES (1, 57);
INSERT INTO public.papel_url VALUES (1, 58);
INSERT INTO public.papel_url VALUES (1, 59);
INSERT INTO public.papel_url VALUES (1, 60);
INSERT INTO public.papel_url VALUES (1, 61);
INSERT INTO public.papel_url VALUES (1, 62);
INSERT INTO public.papel_url VALUES (1, 63);
INSERT INTO public.papel_url VALUES (1, 64);
INSERT INTO public.papel_url VALUES (1, 65);
INSERT INTO public.papel_url VALUES (1, 66);
INSERT INTO public.papel_url VALUES (1, 67);
INSERT INTO public.papel_url VALUES (1, 68);
INSERT INTO public.papel_url VALUES (1, 69);
INSERT INTO public.papel_url VALUES (1, 70);
INSERT INTO public.papel_url VALUES (1, 71);
INSERT INTO public.papel_url VALUES (1, 72);
INSERT INTO public.papel_url VALUES (1, 73);

