<?php

require("../common.php");
require("../lib/InvData.php3");


$ref_curso      = $_POST['ref_curso'];
$ref_disciplina = $_POST['ref_disciplina'];
$ref_campus     = $_POST['ref_campus'];


$hasmore = false;

function ListaCursosDisciplinas()
{
	global $ref_curso, $ref_disciplina, $ref_campus, $hasmore;

	// cores fundo
	$bg0 = "#000000";
	$bg1 = "#EEEEFF";
	$bg2 = "#FFFFEE";

	// cores fonte
	$fg0 = "#FFFFFF";
	$fg1 = "#000099";
	$fg2 = "#000099";

	if (($ref_curso!='') || ($ref_disciplina!='') || ($ref_campus!=''))
	{

		echo("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");

		for ($aux=0; $aux<2; $aux++)
		{
			$conn = new Connection;

			$conn->Open();

			$sql = " select A.ref_curso, " .
             "        B.id, " .
       	     "        B.descricao_disciplina, " .
      	     "        C.id, " .
             "        C.nome_campus, " .
      	     "        B.num_creditos, " .
             "        B.carga_horaria, " .
  	         "        A.curriculo_mco, " .
  	         "        A.equivalencia_disciplina, " .
      	     "        A.dt_final_curriculo, " .
             "        A.semestre_curso, " .
             "        A.fl_soma_curriculo " .
             "  from cursos_disciplinas A, disciplinas B, campus C" .
             "  where A.ref_disciplina=B.id and " .
  	         "        A.ref_campus = C.id ";

			if ($aux == 0)
			{
				$sql .= " and A.curriculo_mco in ('M','C','A') ";
			}
			else
			{
				$sql .= " and A.curriculo_mco not in ('M','C','A') ";
			}

			$where = '';

			if ( $ref_curso != '' )
			{
				$where .= "and A.ref_curso = $ref_curso ";
			}

			if ( $ref_disciplina != '' )
			{
				$where .= "and B.id = $ref_disciplina ";
			}

			if ( $ref_campus != '' )
			{
				$where .= "and C.id = $ref_campus ";
			}

			$sql .= $where . " order by A.semestre_curso, B.descricao_disciplina";

			$query = $conn->CreateQuery($sql);

			$tot_disciplinas = 0;
			$tot_num_creditos = 0;
			$tot_carga_horaria = 0;

			for ( $i=0; $query->MoveNext(); $i++ )
			{
				list ( $ref_curso,
				$id_disciplina,
				$descricao_disciplina,
				$id_campus,
				$nome_campus,
				$num_creditos,
				$carga_horaria,
				$curriculo_mco,
				$equivalencia_disciplina,
				$dt_final_curriculo,
				$semestre_curso,
				$fl_soma_curriculo) = $query->GetRowValues();

				if ($equivalencia_disciplina == 0)
				{
					$equivalencia_disciplina = '&nbsp;';
				}

				if ($i == 0)
				{
					echo("  <tr bgcolor=\"$bg0\">\n");
					//            echo("    <td width=\"4%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">&nbsp;</font></b></td>\n");
					echo("    <td width=\"7%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">Curso</font></b></td>\n");
					echo("    <td width=\"10%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">Cod</font></b></td>\n");
					echo("    <td width=\"36%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">Disciplina</font></b></td>\n");
					// echo("    <td width=\"10%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">Disc.<br>Equiv.</font></b></td>\n");
					echo("    <td width=\"8%\" align=\"center\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">Per&iacute;odo</font></b></td>\n");
					echo("    <td width=\"5%\" align=\"center\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">Créd</font></b></td>\n");
					echo("    <td width=\"5%\" align=\"center\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">CH</font></b></td>\n");
					//       echo("    <td width=\"10%\" align=\"center\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">Data Final</font></b></td>\n");
					echo("    <td width=\"10%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">Campus</font></b></td>\n");
					echo("    <td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">&nbsp;</font></b></td>\n");
					echo("    <td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">&nbsp;</font></b></td>\n");
					echo("  </tr>\n");
				}

				$dt_final_curriculo = InvData($dt_final_curriculo);

				if ((!$dt_final_curriculo) && ($fl_soma_curriculo == 't'))
				{
					$tot_num_creditos += $num_creditos;
					$tot_carga_horaria += $carga_horaria;
					$tot_disciplinas = $tot_disciplinas + 1;
				}
				$href2 = '&nbsp';

				if ( $i % 2 )
				{
					$bg = $bg1;
					$fg = $fg1;
				}

				else
				{
					$bg = $bg2;
					$fg = $fg2;
				}

				$href  = "<a href=\"cursos_disciplinas_edita.phtml?ref_curso=$ref_curso&ref_disciplina=$id_disciplina&ref_campus=$id_campus\"><img src=\"../images/update.gif\" title='Alterar' align='absmiddle' border=0></a>";
				$href3 = "<a href=\"javascript:Confirma_Exclui('$ref_curso','$id_disciplina','$id_campus')\"><img src=\"../images/delete.gif\" title='Excluir' align='absmiddle' border=0></a>";

				echo("  <tr bgcolor=\"$bg\">\n");
				//        echo("    <td width=\"4%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$href2</font></b></td>\n");
				echo("    <td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$ref_curso</font></b></td>\n");
				echo("    <td width=\"8%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$id_disciplina</font></b></td>\n");
				echo("    <td width=\"36%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$descricao_disciplina</font></b></td>\n");
				//       echo("    <td width=\"10%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">&nbsp;$equivalencia_disciplina</font></b></td>\n");
				echo("    <td width=\"5%\" align=\"center\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$semestre_curso</font></b></td>\n");
				echo("    <td width=\"5%\" align=\"center\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$num_creditos</font></b></td>\n");
				echo("    <td width=\"5%\" align=\"center\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$carga_horaria</font></b></td>\n");
				//    echo("    <td width=\"10%\" align=\"center\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$dt_final_curriculo</font></b></td>\n");
				echo("    <td width=\"16%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$nome_campus</font></b></td>\n");
				echo("    <td width=\"3%\" align=\"center\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$href</font></b></td>\n");
				echo("    <td width=\"3%\" align=\"center\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$href3</font></b></td>\n");
				echo("  </tr>\n");

			}

			if ($tot_disciplinas > 0)
			{
				echo(" <tr><td colspan=\"11\">&nbsp;</td></tr>");

				echo(" <tr bgcolor=\"$bg0\">\n");
				echo("  <td  colspan=\"3\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">Totais: Créditos: $tot_num_creditos</font></b></td>\n");
				echo("  <td  colspan=\"3\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">Disciplinas: $tot_disciplinas</font></b></td>\n");
				echo("  <td  colspan=\"3\" align=\"right\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">Carga Horária: $tot_carga_horaria</font></b></td>\n");
				echo(" </tr>\n");

				echo("<tr><td colspan=\"11\">&nbsp;</td></tr>");

			}

			$query->Close();

			$conn->Close();
		}
		echo("</table>");

	}
}
?>
<html>
<head>
<title>Cursos Disciplinas</title>
<script language="JavaScript">
function _init()
{
  document.selecao.ref_curso.focus();
}

function ChangeCode(fld_name,op_name)
{
  var field = eval('document.myform.' + fld_name);
  var combo = eval('document.myform.' + op_name);
  var code  = field.value;
  var n     = combo.options.length;
  for ( var i=0; i<n; i++ )
  {
    if ( combo.options[i].value == code )
    {
      combo.selectedIndex = i;
      return;
    }
  }

  alert(code + ' não é um código válido!');

  field.focus();

  return true;
}

function ChangeOp1()
{
  ChangeOption(document.myform.op1,document.myform.ref_curso);
}

function buscacurso()
{
  tipo_busca=1;

  var url = "../generico/post/lista_cursos_nome.php3" +
   	    "?id=" + escape(document.selecao.ref_curso.value);  

var wnd = window.open(url,'busca','toolbar=no,width=550,height=350,scrollbars=yes');
}

function setResult(arg1)
{
  if (tipo_busca == 1)
  {
    document.selecao.ref_curso.value = arg1;
  }

}

function Confirma_Exclui(arg1, arg2, arg3)
{
    url = 'post/cursos_disciplinas_exclui.php3?ref_curso=' + arg1 + '&ref_disciplina=' + arg2 + '&ref_campus=' + arg3;

  if (confirm("Você tem certeza que deseja EXCLUIR a Disciplina "+arg2+" do Curso "+arg1+" no Campus "+arg3))
    location=(url)
  else
    alert("Exclusão Cancelada.");
}
</script>
<link href="../estilo.css" rel="stylesheet" type="text/css" />
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20"
	onload="_init()">
<form method="post" action="consulta_inclui_cursos_disciplinas.phtml"
	name="selecao">
<div align="center">
<div class="titulo" align="center"><h2>Cursos/Disciplinas (Matriz curricular)</h2></div>
<p><input type="button" value=" Incluir "
	onClick="location='cursos_disciplinas.phtml'" name="button"></p>
<hr align="center" width="500">
<p><font face="Verdana, Arial, Helvetica, sans-serif" size="2"
	color="#0000FF"><b><font color="#FF0000">CUIDADO PARA N&Atilde;O
DUPLICAR CADASTROS !</font></b></font></p>
<table width="90%" border="0" cellspacing="0" cellpadding="2">
	<tr bgcolor="#0066CC">
		<td colspan="6" height="28">
		<div align="center"><font size="2" color="#FFFFFF"><b><font
			face="Verdana, Arial, Helvetica, sans-serif">Consulta/Altera&ccedil;&atilde;o
		de Cursos/Disciplinas</font></b></font></div>
		</td>
	</tr>
	<tr>
		<td width="1">&nbsp;</td>
		<td width="80"><font face="Verdana, Arial, Helvetica, sans-serif"
			size="2">&nbsp;C&oacute;digo do Curso:</font></td>
		<td width="80"><font face="Verdana, Arial, Helvetica, sans-serif"
			size="2">&nbsp;C&oacute;digo da Disciplina:</font></td>
		<td width="80"><font face="Verdana, Arial, Helvetica, sans-serif"
			size="2">&nbsp;C&oacute;digo do Campus:</font></td>
		<td width="80">&nbsp;</td>
		<td width="1">&nbsp;</td>
	</tr>
	<tr>
		<td width="1">&nbsp;</td>
		<td width="80">
		<div align="left"><input name="ref_curso" type=text size="10"
			value="<?echo($ref_curso)?>" onChange="ChangeCode('ref_curso','op1')">
		<input type="button" value="..." onClick="javascript:buscacurso()"
			name="button22"></div>
		</td>
		<td width="80"><input type="text" name="ref_disciplina" size="10"
			value="<?echo($ref_disciplina)?>"></td>
		<td width="80"><input type="text" name="ref_campus" size="10"
			value="<?echo($ref_campus)?>"></td>
		<td width="80">
		<div align="right"><input type="submit" name="botao" value="Localizar">
		</div>
		</td>
		<td width="1">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="6" align="center">
		<hr size="1" width="500">
		</td>
	</tr>
	<tr>
		<td colspan="6"><?PHP ListaCursosDisciplinas(); ?> <font
			face="Verdana, Arial, Helvetica, sans-serif"><font size="2"><b><font
			color="#FF0000"></td>
	</tr>
</table>

</form>
</body>
</html>
