<?php 

require("../common.php"); 

$id = $_GET['id'];


CheckFormParameters(array("id"));

$conn = new Connection;

$conn->Open();

$sql = "select " .
       "    id," .
       "    nome," .
       "    sucinto, " .
       "    nome_atual" .
       "  from instituicoes where id = '$id'";

$query = $conn->CreateQuery($sql);

SaguAssert($query && $query->MoveNext(),"Registro n&atilde;o encontrado!");

list ( $id,
       $nome,
       $sucinto,
       $nome_atual) = $query->GetRowValues();

$query->Close();

$conn->Close();

?>
<html>
<head>
<link rel="stylesheet" href="<?=$BASE_URL .'public/styles/required.css'?>" type="text/css">
<script language="JavaScript">
  function _init()
  {
    document.myform.nome.focus();
  }
</script>
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20" onload="_init()">
<form method="post" action="post/instituicao_altera.php3" name="myform">
  <div align="center">
    <table width="90%" align="center">
      <tr bgcolor="#000099"> 
        <td height="35" colspan="2">
          <div align="center"><font size="3" face="Verdana, Arial, Helvetica, sans-serif"><b><font color="#CCCCFF">Altera&ccedil;&atilde;o de Institui&ccedil;&atilde;o</font></b></font></div>
        </td>
      </tr>
      <tr> 
        <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;C&oacute;digo&nbsp;</font></td>
        <td> <font face="Verdana, Arial, Helvetica, sans-serif" color="#FF0033"> 
          <input type="hidden" name="id" value="<? echo($id); ?>">
          <?php echo($id); ?></font></td>
      </tr>
      <tr> 
        <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Nome da Institui&ccedil;&atilde;o&nbsp;<span class="required">*</span>&nbsp;</font></td>
        <td> 
          <input name="nome" type=text value="<?echo($nome);?>" size="40">
        </td>
      </tr>
      <tr> 
        <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Sucinto&nbsp;</font></td>
        <td> 
          <input name="sucinto" type=text value="<?echo($sucinto);?>" size="40">
        </td>
      </tr>
      <tr> 
        <td bgcolor="#CCCCFF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#00009C">&nbsp;Nome Atual&nbsp;</font></td>
        <td> 
          <input name="nome_atual" type=text value="<?echo($nome_atual);?>" size="40">
        </td>
      </tr>
      <tr> 
        <td colspan="2"> 
          <hr size="1">
        </td>
      </tr>
      <tr> 
        <td colspan="2" align="center"> 
          <input type="submit" name="Submit"  value=" Salvar ">
          <input type="button" name="Submit2" value=" Voltar " onclick="javascript:history.go(-1)">
        </td>
      </tr>
    </table>
  </div>
</form>
</body>
</html>
