<?php

require_once("../common.php");

$nome = $_POST['nome'];
$nome_completo = $_POST['nome_completo'];

$hasmore = false;

function ListaPessoas()
{
	global $nome, $nome_completo, $hasmore;
	global $like;

	$nome_completo = strtoupper($nome_completo);

	$count = 0;

	$like = "";

	if ( $nome != "" )
	$like = "$nome";

	if ( $nome_completo != "" )
	$like = "$nome_completo%";

	else if ( $like != "" )
	$like = "$like%";
	 
	if ( $like != "" )
	{
		// cores fundo
		$bg0 = "#000000";
		$bg1 = "#EEEEFF";
		$bg2 = "#FFFFEE";

		// cores fonte
		$fg0 = "#FFFFFF";
		$fg1 = "#000099";
		$fg2 = "#000099";

		$conn = new Connection;

		$conn->Open();

		$sql = " select nome, " .
           "        nome_completo " .
           " from usuario ";

		$where = '';

		if ( $nome != '' )
		{
			$where .= ( $where == '' ) ? ' where ' : ' and ';
			$where .= "nome = '$nome'";
		}

		if ( $nome_completo != '' )
		{
			$where .= ( $where == '' ) ? ' where ' : ' and ';
			$where .= "upper(nome_completo) like upper('$nome_completo%')";
		}

		$sql .= $where . " order by nome";

		$query = $conn->CreateQuery($sql);

		echo("<table width=\"490\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");

		echo("  <tr bgcolor=\"$bg0\">\n");
		echo("    <td width=\"20%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">Login</font></b></td>\n");
		echo("    <td width=\"70%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">Nome do Usuário</font></b></td>\n");
		echo("    <td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">&nbsp;</font></b></td>\n");
		echo("    <td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg0\">&nbsp;</font></b></td>\n");
		echo("  </tr>\n");

		for ( $i=0; $i<25 && $query->MoveNext(); $i++ )
		{

			list ( $nome, $nome_completo ) = $query->GetRowValues();

			if ( $i % 2 )
			{
				$bg = $bg1;
				$fg = $fg1;
			}

			else
			{
				$bg = $bg2;
				$fg = $fg2;
			}

			$href  = "<a href=\"perfil_edita.phtml?nome=$nome\"><img src=\"../images/update.gif\" alt='Alterar Usuário' align='absmiddle' border=0></a>";
			$href1 = "<a href=\"javascript:Confirma_Exclui('$nome')\"><img src=\"../images/delete.gif\" alt='Excluir Usuário' align='absmiddle' border=0></a>";


			echo("  <tr bgcolor=\"$bg\">\n");
			echo("    <td width=\"20%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$nome</font></b></td>\n");
			echo("    <td width=\"70%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$nome_completo</font></b></td>\n");
			echo("    <td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$href</font></b></td>\n");
			echo("    <td width=\"5%\"><b><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=\"$fg\">$href1</font></b></td>\n");
			echo("  </tr>\n");
		}

		echo("</table>");

		$hasmore = $query->MoveNext();

		$query->Close();

		$conn->Close();

		$count = $i;
	}

	else
	echo("<br><center><font face=\"Verdana, Arial, Helvetica, sans-serif\" size=\"2\" color=red><b>Informe um campo para fazer a pesquisa!</b></font></center><br>");

	return $count;
}
?>
<html>
<head>
<title></title>
<script language="JavaScript">
function _init()
{
   document.selecao.id.focus();
}

function Confirma_Exclui(arg1)
{
  url = 'perfil_exclui.php?nome=' + arg1;

  if (confirm("Você tem certeza que deseja EXCLUIR o usuário: "+arg1+" ?"))
    location=(url)
  else
    alert("Exclusão Cancelada.");
}
</script>
<link href="../estilo.css" rel="stylesheet" type="text/css" />
</head>
<body bgcolor="#FFFFFF" marginwidth="20" marginheight="20"
	onload="_init()">
<form method="post" action="consulta_inclui_usuarios.phtml"
	name="selecao">
<div align="center">
<div class="titulo"><h2>Usu&aacute;rios do sistema</h2></div>
<p><input type="button" value=" Incluir Usuário "
	onClick="location='perfil_inclui.phtml'" name="button"></p>
<hr>
<p><font face="Verdana, Arial, Helvetica, sans-serif" size="2"
	color="#0000FF"><b><font color="#FF0000">CUIDADO PARA N&Atilde;O
DUPLICAR CADASTROS !</font></b></font></p>
<table width="500" border="0" cellspacing="0" cellpadding="2"
	height="268">
	<tr bgcolor="#0066CC">
		<td colspan="4" height="28">
		<div align="center"><font size="2" color="#FFFFFF"><b><font
			face="Verdana, Arial, Helvetica, sans-serif">Consulta/Altera&ccedil;&atilde;o
		de Usuários</font></b></font></div>
		</td>
	</tr>
	<tr>
		<td width="1">&nbsp;</td>
		<td width="102"><font face="Verdana, Arial, Helvetica, sans-serif"
			size="2">&nbsp;Login:</font></td>
		<td width="311"><font face="Verdana, Arial, Helvetica, sans-serif"
			size="2">&nbsp;Nome:</font></td>
		<td width="74">&nbsp;</td>
	</tr>
	<tr>
		<td width="1">&nbsp;</td>
		<td width="102">
		<div align="left"><input type="text" name="nome" size="15"
			value="<?echo($nome)?>"></div>
		</td>
		<td width="311"><input type="text" name="nome_completo" size="40"
			value="<?echo($nome_completo)?>"></td>
		<td width="74">
		<div align="right"><input type="submit" name="botao" value="Localizar">
		</div>
		</td>
	</tr>
	<tr>
		<td colspan="4" align="center">
		<hr size="1" width="490">
		</td>
	</tr>
	<tr>
		<td colspan="4"><? ListaPessoas(); ?> <font
			face="Verdana, Arial, Helvetica, sans-serif"><font size="2"><b><font
			color="#FF0000"> <?  if ( $hasmore )
			echo("<BR><center>Se o usuário não estiver listado, seja mais específico.</center>"); ?>
		</font></b></font></font></td>
	</tr>
	<tr align="center">
		<td colspan="4">
		<hr size="1" width="490">
		</td>
	</tr>
	<tr align="center">
		<td colspan="4" height="134">
		<div align="left">
		<ul>
			<li><font face="Arial, Helvetica, sans-serif" size="2"
				color="#0000CC"><b><font
				face="Verdana, Arial, Helvetica, sans-serif">Se o usuário que
			voc&ecirc; pesquisou estiver presente na lista pesquisada, n&atilde;o
			&eacute; necess&aacute;rio inclu&iacute;-lo novamente.</font></b></font></li>
			<li><b><font face="Verdana, Arial, Helvetica, sans-serif" size="2"
				color="#0000CC">Se voc&ecirc; quiser consultar ou alterar os dados
			de um usuário da lista pesquisada, clique na imagem correspondente.</font></b></li>
			<li><font face="Arial, Helvetica, sans-serif" size="2"
				color="#0000CC"><b><font
				face="Verdana, Arial, Helvetica, sans-serif">Se o usuário n&atilde;o
			estiver na lista acima, ele n&atilde;o est&aacute; cadastrado no
			sistema. Clique no bot&atilde;o &quot;Incluir Usuário&quot; para
			fazer um novo cadastro.</font></b></font></li>
		</ul>
		</div>
		</td>
	</tr>
</table>
<font face="Verdana, Arial, Helvetica, sans-serif"><font size="2"><b><font
	color="#FF0000"> </font></b></font></font></div>
</form>
</body>
</html>
